log:
  level: INFO
  
entryPoints:
  websecure:
    address: ":443"

providers:
  docker:
    network: http-net
    exposedByDefault: false

certificatesResolvers:
  tls-resolver:
    acme:
      storage: /etc/traefik/acme.json
      tlsChallenge: {}
      httpChallenge:
        entryPoint: websecure
  